export const SIGNUP_SUCCESS = "REGISTER_SUCCESS";
export const SIGNUP_FAIL = "REGISTER_FAIL";
export const SIGNUP_ERROR = "REGISTER_ERROR";
export const SIGNUP_ON_CHANGE = "REGISTER_ON_CHANGE";
export const SIGNUP_CLEAR = "REGISTER_CLEAR";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGIN_ON_CHANGE = "LOGIN_ON_CHANGE";
export const LOGIN_CLEAR = "LOGIN_CLEAR";

export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL";
export const FORGOT_PASSWORD_ONCHANGE = "FORGOT_PASSWORD_ONCHANGE";
export const FORGOT_PASSWORD_ERROR = "FORGOT_PASSWORD_ERROR";
export const FORGOT_PASSWORD_CLEAR = "FORGOT_PASSWORD_CLEAR";

export const NEW_PASSWORD_SUCCESS = "NEW_PASSWORD_SUCCESS";
export const NEW_PASSWORD_FAIL = "NEW_PASSWORD_FAIL";
export const NEW_PASSWORD_ONCHANGE = "NEW_PASSWORD_ONCHANGE";
export const NEW_PASSWORD_ERROR = "NEW_PASSWORD_ERROR";
export const NEW_PASSWORD_CLEAR = "NEW_PASSWORD_CLEAR";

export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";
export const RESET_PASSWORD_ONCHANGE = "RESET_PASSWORD_ONCHANGE";
export const RESET_PASSWORD_ERROR = "RESET_PASSWORD_ERROR";
export const RESET_PASSWORD_CLEAR = "RESET_PASSWORD_CLEAR";

export const SHOW_STUDENTDATA = "SHOW_STUDENTDATA";
export const SHOW_STUDENTDATA_ERROR = "SHOW_STUDENTDATA_ERROR";

export const SHOW_VERIFIED_STUDENTDATA = "SHOW_VERIFIED_STUDENTDATA";
export const SHOW_VERIFIED_STUDENTDATA_ERROR =
  "SHOW_VERIFIED_STUDENTDATA_ERROR";

export const VIEW_STUDENT_DETAIL = "VIEW_STUDENT_DETAIL";
export const VIEW_STUDENT_DETAIL_ERROR = "VIEW_STUDENT_DETAIL_ERROR";

export const CREATE_EXAM_SUCCESS = "CREATE_EXAM_SUCCESS";
export const CREATE_EXAM_FAIL = "CREATE_EXAM_FAIL";

export const VIEW_EXAM_SUCCESS = "VIEW_EXAM_SUCCESS";
export const VIEW_EXAM_ERROR = "VIEW_EXAM_ERROR";

export const VIEW_EXAM_DETAIL_SUCCESS = "VIEW_EXAM_DETAIL_SUCCESS";
export const VIEW_EXAM_DETAIL_ERROR = "VIEW_EXAM_DETAIL_ERROR";

export const DELETE_EXAM = "DELETE_EXAM";
